services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: todolist-postgres
    environment:
      POSTGRES_DB: proyecto0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Go
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todolist-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: proyecto0
      DB_SSL_MODE: disable
      SERVER_PORT: 8080
      JWT_SECRET: super-secret-change-this-in-production
      ENV: production
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todolist-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  todolist-network:
    driver: bridge
